org: corylogan
app: together
service:
  name: image-resizing

provider:
  name: aws
  runtime: nodejs12.x
  tracing:
    apiGateway: true
    lambda: true
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - s3:*
      Resource: 'arn:aws:s3:::together-blog/*'
      # Fn::Join: ['', [Fn::GetAtt: [ AssetBucket, Arn ], '/*'] ]

plugins:
  - serverless-webpack

package:
  individually: true

functions:
  resize:
    handler: src/handlers/resize-images.handler
    package:
      exclude:
        - '**/**'
      include:
        - src/handlers/resize-images.ts
    events:
      - s3:
          bucket: together-blog
          event: s3:ObjectCreated:*
          # existing: true
          # rules:
          #   - prefix: originals/

    environment:
      REGION: us-east-1
    iamRoleStatements:
      - Effect: 'Allow'
        Action:
          - 's3:GetObject'
        Resource: 'arn:aws:s3:::together-blog/*'
      - Effect: 'Allow'
        Action:
          - 's3:PutObject'
        Resource: 'arn:aws:s3:::together-blog/*'
layers:
  exiftool:
    path: ./layers/exiftool
    allowedAccounts:
      - '*'

resources:
  Resources:
    AssetBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: together-blog-processing

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    packager: 'yarn'
    includeModules: false
